### ISSUE TITLE
Mention that Ohm still supports matching sequences not just strings

### ISSUE THREAD

**Issue by vkz** [cdglabs/ohm#106]
Maybe I'm just thick and it's completely obvious to everyone else but until I [actually tried](http://jsfiddle.net/r74mdq5t/1/) I was totally convinced that unlike its predecessor Ohm only supports matching strings. Far as I can tell neither docs nor any example explicitly show or even mention matching JS arrays. The only reason that made me try instead of going away unsatisfied was the type annotation for `Grammar.match` in the [API reference](https://github.com/cdglabs/ohm/blob/master/doc/api-reference.md#grammar-objects).

Also, tangentially related question. Is it a fair assessment that when matching arrays returned failure position isn't well specified?  I got `0` and sometimes `-1`. Does this mean that debugging for arrays isn't as well support at the moment as for strings? Thank you.

**Comment by pdubroy** [comment]
Hi Vlad,

Thanks for raising this. The reason it's confusing is that we recently (as of v0.11.0, published 5 days ago) removed support for matching on Arrays and Objects. There were a couple reasons for this:

1. It complicates the implementation and several parts of the API, and
2. we found that Ohm's design -- particularly the ability to define multiple semantic operations that require only a single parsing pass -- make this feature much less useful than it was in OMeta.

The reason it still worked on JSFiddle was that I had forgotten to update that to the latest version -- but I've done that now.

So, sorry if this is a feature that you were hoping for -- but we think Ohm will be better without it in the end. Focusing on string matching will allow us to keep the implementation and documentation simpler, and possibly enable some optimizations that wouldn't be possible otherwise.

**Comment by vkz** [comment]
Thank you!

Looking at the [commits that went into v0.10.0](https://github.com/cdglabs/ohm/compare/v0.10.0...master) seems like the latest commit that still had full support was [3a8c3eb](https://github.com/cdglabs/ohm/commit/3a8c3eb044da410d8dbfa851f27881a7426d85c0). Is that right? I might still try it if only to see how well it works for my task.
