### ISSUE TITLE
Javascript code generation for parsers

### ISSUE THREAD

**Issue by kkeri** [cdglabs/ohm#117]
A moderately complex Ohm parser (the lexer part of ES5.ohm) takes seconds to compile for me. I'm trying to eliminate startup delays. With Ometajs (and also with other parser generators) I was able to generate js source code for my parsers.

Do you plan this feature, or even better, is there already a solution to my problem in Ohm?

**Comment by tonyg** [comment]
This area is still, as I understand it, being discussed, but I wonder if `Grammar.toRecipe()` (see [here](https://github.com/cdglabs/ohm/blob/master/src/Grammar.js#L144) and [here](https://github.com/cdglabs/ohm/blob/master/src/pexprs-outputRecipe.js#L47-L126)) might help? This is the mechanism Ohm uses to bootstrap itself. Some caution is in order, though, because [this branch](https://github.com/cdglabs/ohm/tree/json-recipes), which might be merged soon, alters `outputRecipe` to produce a JSON object rather than code containing calls to the Ohm runtime library. (The JSON approach is useful for portability when bootstrapping Ohm implementations.)

**Comment by kkeri** [comment]
@tonyg: Thanks, I guess this will be useful. I'm fine with the JSON approach too, as long as my intent is to reduce startup times.

In `Grammar.js` I also found example of using the pexprs API directly, something I might be interested in the future (think of generating grammars pragramatically). But it is another story.

**Comment by mroeder** [comment]
@kkeri: I have just taken some measurements using `ohm.makeRecipe()` and a recipe should be about 20x faster for the ES5 grammar than parsing it every time!
Note that the *current* syntax for using it is `ohm.makeRecipe(eval(es5.toRecipe()))` (`ohm.makeRecipe` takes a JS function) and will change to `ohm.makeRecipe(es5.toRecipe())` when switching over to [JSON-recipes](./109).

**Comment by kkeri** [comment]
@mroeder: sounds good. I give it a try.

**p.s.:** In the meantime I recognized that my parser compiles significantly faster when I invoke node.js from the command line (I'm debugging with VS community otherwise).
