### ISSUE TITLE
Rule descriptions in override and extend

### ISSUE THREAD

**Issue by codeZeilen** [cdglabs/ohm#25]
With the new rule description syntax, would it be possible to also add rule descriptions to overriding and extending rules?

Something along these lines:

````
  Rule
    = ident Formals? ruleDescr? "="  Alt  -- define
    | ident Formals?  ruleDescr? ":=" Alt  -- override
    | ident Formals?  ruleDescr? "+=" Alt  -- extend
````

**Comment by alexwarth** [comment]
Hi Patrick,

That's true, yes. But I made deliberate decision not to support the overriding of rule descriptions, the reason being that overriding shouldn't change the meaning of the rule, so the original description should still make sense. It's possible this was too heavy-handed, and should be revisited -- we won't know for sure until we've had more experience using Ohm.

What do you think? Have you found this to be annoying in practice? Do you have examples of (reasonable) things that you wanted to do and weren't allowed because of this restriction?

Cheers,
Alex

**Comment by codeZeilen** [comment]
Hi Alex,
actually the one use case that I encountered was adding a rule description to an extending rule. This happened when I extended the space rule in my OhmSmalltalk grammar to also include comments. Not sure if this already qualifies for a reasonable use case :) 

Maybe it'll be best to watch out for other situations and decide later on.

Bests

**Comment by pdubroy** [comment]
I'm going to go ahead and close this for now, and we can re-open if we come up with any other good use cases.
