### ISSUE TITLE
null vs. undefined keyword question

### ISSUE THREAD

**Issue by justinmchase** [cdglabs/ohm#40]
```
null: Matches a null value (or the equivalent in the host language).
```

What about undefined? In javascript at least undefined exists, would the null keyword match null and undefined, or how is undefined handled?

**Comment by pdubroy** [comment]
There's currently no way to match the value `undefined`. We use strict equals to compare values, and `null !== undefined`. Since undefined is a major footgun in JS, I'm tempted to leave things the way they are. The semantics would be more than a little confusing anways -- e.g., what would the pattern `{job: undefined, ...}` mean? Would an object without a `job` field match it, or not?

That said, I'm definitely willing to reconsider if there are good reasons to support it.

**Comment by justinmchase** [comment]
For properties on objects it would be interesting to do:
```
{ ~job }
```
Meaning the job property is undefined on that object. For a value in an array though, maybe just a negation operator without an expression?
```
[ ~ ]
```
or:
```
example = letter ~ letter
```
Which matches `['a', undefined, 'b']` ?

as opposed to:
```
example = letter ~letter
```
Which matches `['a', 3]`

I don't really know I'm just spitballing.

**Comment by alexwarth** [comment]
I'm with Pat on this. We would need see a couple of compelling examples of why you'd want to match an object that does not contain a certain property.

**Comment by pdubroy** [comment]
I can see it being useful to match on objects that do not have a certain property, though it should already be possible with something like `~{ job: _, ...} {...}`. (I assume that is what you meant by "the job property is undefined on that object" -- because in JS `x.job = undefined` is something different.) 

I'm going to close this issue since it's about `undefined` vs. `null`. Feel free to open a separate issue if you'd like to discuss a syntax for matching objects that don't have a particular property.

**Comment by justinmchase** [comment]
I agree that the property missing feature is a separate discussion and should be a different topic (if its needed at all). And also that `{ job: undefined }` is not the same as `{ }` in javascript.

But the value `undefined` is pretty important in js and I think you will need to support the ability to match on it. It will be needed for the same reasons why you would need to match on null. I know that null and undefined are not supposed to be semantically the same thing but in javascript, especially if you depend on 3rd party libraries its a crapshoot which one you'll actually get.

For example, suppose we have the array `[1, undefined, 3]` and I want to use a rule such as `(number | undefined)*`. How can I do that? I think the only way would be to use `any*` and then use semantics to do all the work. Or write a manual step that pre-processes the structure replacing `undefined`s with `null`s and then run it through the rule `(number | null)*`.

It would be super easy to just add an undefined. It would be  just like the `null` rule, but strictly compares to undefined instead. The complicating factor, as far as I understand it, is that ohm grammar is host-language agnostic and therefore is not javascript specific and since most languages are saner than javascript they don't have both null and undefined. Therefore your decision to not add an undefined match rule makes sense to me, except that you still need a way to match it when in javascript.

One other possibility would be to just specify that null also matches undefined. You could change the `null` rule implementation from:
```
return value === null;
```
to:
```
// double equals against null also matches undefined
// http://www.ecma-international.org/ecma-262/5.1/#sec-11.9.3
return value == null;
```

Maybe I'm making a bigger deal out of this than is really needed but it seems correct to me that you are going to  need a way to match `undefined`s.

**Comment by pdubroy** [comment]
In my opinion, it's bad practice to store `undefined` values in data structures, for two reasons:

- It's confusing when you fetch the value. If `arr[1]` is undefined, it's not immediately clear whether it's an out-of-bounds index or whether the value stored there at [1] was `undefined`.
- It is often a symptom of an error elsewhere in the program, e.g. `arr.push(obj.tpyo)`.

As you pointed out, Ohm grammars are supposed to be host-language-agnostic, so that's the main reason that I'd be quite hesitant to support it. There's always the option to preprocess the structure if you need to match something from a 3rd party library -- but can you give any examples of libraries that produce objects like this? My feeling is that it's not very common.

Finally, we've tried to keep our object/array patterns similar to JSON, since those choices have proven to work pretty well across languages. JSON doesn't have `undefined`, and I've never run into problems because of it.

Actually, one option would be to do what JSON.stringify does -- treat a property with an undefined value to mean the same as a missing property.

**Comment by justinmchase** [comment]
Here is an example of a project using undefined instead of null:
https://github.com/chrisdew/protobuf

It reads protobuf data structures from Buffer objects and can produce undefined values. I agree that it should be using null... but it doesn't.

We switched from this project to `protobufjs` and had to swap a lot of undefined to null checks. It was not a lot of fun.

But anyway, i think you get it. That's all I have to say :)

**Comment by pdubroy** [comment]
Interesting, thanks for the example. We'll keep it in mind, but I don't think it's enough to tip the scales. Thanks for the feedback and discussion though.
