### ISSUE TITLE
built in rule recommendation: any

### ISSUE THREAD

**Issue by justinmchase** [cdglabs/ohm#41]
```
_: Matches a single item from the input stream. For a string, it will match any one character.
```

I would recommend an alias for this: `any` (or only using any). In such a token heavy, semantically rich language if you can take advantage of short keywords it seems like a good thing.

**Comment by alexwarth** [comment]
Thanks for the suggestion, Justin! Pat and I agree that `any` would be more readable than `_` in Ohm, and I'm about to push a commit that makes this change. FWIW, I don't think that we should have any built-in rules that encourage people to write code that is less readable, so I'll rename `_` to `any` instead of making the latter an alias.

**Comment by alexwarth** [comment]
Commit pushed.

**Comment by justinmchase** [comment]
nice :)
