### ISSUE TITLE
Matching with parameterized start rule does not work

### ISSUE THREAD

**Issue by mroeder** [cdglabs/ohm#76]
`grammar.match(input)` can be passed a second, optional rule name to start parsing the `input` from that rule.
Currently parameterized rules like `Foo<arg>` cannot be use and matched. This turns out to be a specific problem with e.g. the [ES5 grammar](../blob/master/examples/ecmascript/es5.ohm) where `<guardIn>` is used now.

For the ES5 grammar, a call with a reference to a defined rule (instead of a specific value) would be necessary/sufficient:
`g.match('1+2', 'Expression<withIn>');` for `Expression<guardIn>`

**Comment by mroeder** [comment]
A possible (tried) solution would be to:
* extend `Grammar.prototype.match(obj, optStartRule)` with a third, optional prototype that takes an array of arguments,
* forward those parameters via `opts.actuals` to `Grammar.prototype.match(values, startRules, opts)` and call the `Apply` with those actuals as args.

That would mean that the describe call for ES5 could be:
`g.match('1+2', 'Expression', [new ohm.pexprs.Apply('withIn')]);`

Another approach could be to parse the optional rule name into rule name and parameters to be able to call `g.match('1+2', 'Expression<withIn>')` without knowledge about the `pexprs` interface.

**Comment by pdubroy** [comment]
I can see how this would be useful for debugging, but do you have another use case in mind? Having a specific example would help in deciding on a solution. I think both of things you proposed could work.

If we think it's something that people will want to use for test cases in the editor (and I think it is), then the second solution might be best, because in that scenario I'd imagine people won't be writing the `g.match(...)` code directly...they'd have a combo box or something where they can pick a start rule. In that case, I think expressing the start rule in terms of Ohm syntax (rather than JS syntax) is a better fit.

**Comment by alexwarth** [comment]
> Another approach could be to parse the optional rule name into rule name and parameters to be able to call g.match('1+2', 'Expression<withIn>') without knowledge about the pexprs interface.

I like this option much better than the first one, because as you said, it doesn't require knowledge of the pexprs interface. It also seems to work better for the Ohm visualizer / editor, as @dubroy noted.

@mroeder: I'd be happy to give you a hand with this if you'd like. Let me know :)

**Comment by mroeder** [comment]
@pdubroy: The topic came up yesterday with @sakekasi who wanted to parse ES5 expressions for the semantic actions to determine whether there is an implicit return or an explicit one.
But I also think that it would be of good use in the editor.

I will get working on it and have you take a look afterwards...

**Comment by mroeder** [comment]
Fixed by ec1dd5c8b8f9193b1e4fca85dd12a6292a82eec4 and 2ad952d7cb97e6d2c11b1c223992bec13c010f7e.
Thanks @pdubroy!
