### ISSUE TITLE
What does the `#` token mean?

### ISSUE THREAD

**Issue by justinmchase** [cdglabs/ohm#98]
In the ohm grammar it has this:
```
  Modifier
    = "#" Base  -- lex
    | "$" Base  -- val
    | Base
```

Which seems to me to imply it is a lexical modifier!

And in the es5 grammar it has this:
```
ReturnStatement = return (#(spacesNoNL ~space) Expression<withIn>)? #(sc)
```

Where `sc` is, I believe, `semi-colon`. So I'm wondering what the `#` operator means. I tried digging deeper into the ohm grammar semantics but I lost the thread somewhere.

**Comment by alexwarth** [comment]
Hi Justin,

The `#` is Ohm's "lexification" operator -- it can be used inside a syntactic rule to prevent the implicit skipping of whitespace. Without it, the application of `sc` in `ReturnStatement` would not get a chance to inspect any whitespace. This would be problematic because in JS, a newline character can be interpreted as a logical semicolon.

Not closing this issue b/c we should document this feature.

Cheers,
Alex

**Comment by justinmchase** [comment]
While we're at it, what is the `$` also?

**Comment by pdubroy** [comment]
`$` was undocumented because we were planning to remove it, and it is gone now :-)
